### ISSUE TITLE
trident-eval-dwim is not interactive

### ISSUE THREAD

**Issue by synchromesh** [johnmastro/trident-mode.el#2]
Hi, first thanks very much for putting Trident Mode together, I'm finding it very useful for my Parenscript development.

Just a minor thing, I'm no Emacs Lisp guru but it seems to me that `trident-eval-dwim` is missing an initial `(interactive)`.

Cheers,

John :^P

**Comment by johnmastro** [comment]
You're absolutely right. I just pushed fabcfd6 to make it interactive.

I haven't used Parenscript for some time, and thus haven't given this package any attention, but I'm glad it's useful. Thanks for reporting this, and please let me know if you run into any other issues.
